# Generated by Django 3.0 on 2019-12-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='animeinfo',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_anime'),
        ),
    ]
