# Generated by Django 3.0 on 2019-12-14 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20191213_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animeinfo',
            name='following',
        ),
        migrations.AddField(
            model_name='animeinfo',
            name='following_fhd',
            field=models.ManyToManyField(blank=True, related_name='following_fhd', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animeinfo',
            name='following_hd',
            field=models.ManyToManyField(blank=True, related_name='following_hd', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animeinfo',
            name='following_ld',
            field=models.ManyToManyField(blank=True, related_name='following_ld', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animeinfo',
            name='following_sd',
            field=models.ManyToManyField(blank=True, related_name='following_sd', to=settings.AUTH_USER_MODEL),
        ),
    ]
