# Generated by Django 3.0 on 2019-12-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191215_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeinfo',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
